namespace API.Helpers
{
    public class TemplateHelper
    {
        private readonly string _donorName;
        private readonly string _itemList;
        private readonly string _collectionDate;
        private readonly string _donorPhone;

        public TemplateHelper(
            string donorName = "NULL",
            string itemList = "NULL",
            string collectionDate = "NULL",
            string donorPhone = "NULL"
        )
        {
            _donorName = donorName;
            _itemList = itemList;
            _collectionDate = collectionDate;
            _donorPhone = donorPhone;
        }

        public string MessageReject
        {
            get
            {
                return
                @"
                <!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd""><html style=""width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0;""><head><meta charset=""UTF-8""><meta content=""width=device-width, initial-scale=1"" name=""viewport""><meta name=""x-apple-disable-message-reformatting""><meta http-equiv=""X-UA-Compatible"" content=""IE=edge""><meta content=""telephone=no"" name=""format-detection""><title>Accepted-Rejected</title> <!--[if (mso 16)]><style type=""text/css"">     a {text-decoration: none;}     </style><![endif]--> <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><style type=""text/css"">
                @media only screen and (max-width:600px) {p, ul li, ol li, a { font-size:16px!important; line-height:150%!important } h1 { font-size:30px!important; text-align:center; line-height:120%!important } h2 { font-size:26px!important; text-align:center; line-height:120%!important } h3 { font-size:20px!important; text-align:center; line-height:120%!important } h1 a { font-size:30px!important } h2 a { font-size:26px!important } h3 a { font-size:20px!important } .es-menu td a { font-size:16px!important } .es-header-body p, .es-header-body ul li, .es-header-body ol li, .es-header-body a { font-size:16px!important } .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li, .es-footer-body a { font-size:16px!important } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock a { font-size:12px!important } *[class=""gmail-fix""] { display:none!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3 { 
                text-align:center!important } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 { text-align:right!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-button-border { display:block!important } a.es-button { font-size:20px!important; display:block!important; border-width:10px 0px 10px 0px!important } .es-btn-fw { border-width:10px 0px!important; text-align:center!important } .es-adaptive table, .es-btn-fw, .es-btn-fw-brdr, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .es-adapt-td { display:block!important; width:100%!important } .adapt-img { width:100%!important; height:auto!important } .es-m-p0 { padding:0px!important } .es-m-p0r { 
                padding-right:0px!important } .es-m-p0l { padding-left:0px!important } .es-m-p0t { padding-top:0px!important } .es-m-p0b { padding-bottom:0!important } .es-m-p20b { padding-bottom:20px!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { display:table-row!important; width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } .es-desk-menu-hidden { display:table-cell!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } table.es-social { display:inline-block!important } table.es-social td { display:inline-block!important } }#outlook a {	padding:0;}.ExternalClass {	width:100%;}.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {	line-height:100%;}.es-button 
                {	mso-style-priority:100!important;	text-decoration:none!important;}a[x-apple-data-detectors] {	color:inherit!important;	text-decoration:none!important;	font-size:inherit!important;	font-family:inherit!important;	font-weight:inherit!important;	line-height:inherit!important;}.es-desk-hidden {	display:none;	float:left;	overflow:hidden;	width:0;	max-height:0;	line-height:0;	mso-hide:all;}</style></head><body style=""width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0;""><div class=""es-wrapper-color"" style=""background-color:#F6F6F6;""> <!--[if gte mso 9]><v:background xmlns:v=""urn:schemas-microsoft-com:vml"" fill=""t""> <v:fill type=""tile"" color=""#f6f6f6""></v:fill> </v:background><![endif]-->
                <table class=""es-wrapper"" width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;""><tr style=""border-collapse:collapse;""><td valign=""top"" style=""padding:0;Margin:0;""><table class=""es-content"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;""><table class=""es-content-body"" width=""600"" cellspacing=""0"" cellpadding=""0"" bgcolor=""#ffffff"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;""><tr style=""border-collapse:collapse;"">
                <td align=""left"" style=""Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td width=""560"" valign=""top"" align=""center"" style=""padding:0;Margin:0;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;padding-bottom:15px;""><h2 style=""Margin:0;line-height:29px;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:24px;font-style:normal;font-weight:normal;color:#333333;""><strong>Hi " + _donorName + @",</strong></h2></td></tr><tr style=""border-collapse:collapse;"">
                <td align=""center"" style=""Margin:0;padding-top:5px;padding-bottom:20px;padding-left:20px;padding-right:20px;font-size:0;""><table border=""0"" width=""100%"" height=""100%"" cellpadding=""0"" cellspacing=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td class=""es-m-txt-c"" align=""center"" style=""padding:5px;Margin:0;font-size:0px;""><img src=""https://iibpvd.stripocdn.email/content/guids/CABINET_787446a06f57203897723d3c9119271f/images/56811590229581355.jpeg"" alt style=""display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;"" width=""550""></td></tr><tr style=""border-collapse:collapse;"">
                <td align=""left"" style=""padding:0;Margin:0;padding-top:20px;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;"">Thank you for your recent offer to donation your unwanted items - unfortunately we can't accept them at this time. This could be due to the items themselves not being what we need at the moment, or we might simply just be at capacity in our warehouse.&nbsp;<br><br>Here's what you offered us. We hope you can find a good home for them!<br><br></p><strong>" + _itemList + @"</strong></td></tr><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;"">
                <p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;""><br>Thanks again,<br>The Helping Hands Team</p></td></tr><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:20px;Margin:0;font-size:0;""><table border=""0"" width=""100%"" height=""100%"" cellpadding=""0"" cellspacing=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;"">
                <p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#999999;"">House2Home is run by volunteers. A small donation towards your item being collected would be appreciated to keep our charity running.<br><br></p></td></tr><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0;""><a href=""https://uk.virginmoneygiving.com/charity-web/charity/finalCharityHomepage.action?charityId=1015521"" style=""-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:14px;text-decoration:underline;color:#1376C8;""> Click here to donate </a></td></tr><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0;"">
                <a href=""https://docs.google.com/forms/d/e/1FAIpQLSfyGpmIwRakYeLqaN3ZNE9cYXuZsHvseIMGh4GCfz1NllEYOQ/viewform"" style=""-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:14px;text-decoration:underline;color:#1376C8;"">Click here to join our volunteering team</a></td></tr></table></td></tr></table></td></tr></table></td></tr></table><table class=""es-footer"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;"">
                <table class=""es-footer-body"" width=""600"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;""><tr style=""border-collapse:collapse;""><td align=""left"" style=""Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td width=""560"" valign=""top"" align=""center"" style=""padding:0;Margin:0;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:20px;Margin:0;font-size:0;"">
                <table width=""75%"" height=""100%"" cellspacing=""0"" cellpadding=""0"" border=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;padding-top:10px;padding-bottom:10px;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:11px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:17px;color:#333333;"">© 2020 Registered in England: Registration number: 1188613 Charitable Incorporated Organisation (CIO) Name: HELPING HANDS COMMUNITY PROJECT</p></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr>
                </table></div></body>
                </html>
                ";
            }
        }

        public string MessageAccept
        {
            get
            {
                return
                @"
                <!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd""><html style=""width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0;""><head><meta charset=""UTF-8""><meta content=""width=device-width, initial-scale=1"" name=""viewport""><meta name=""x-apple-disable-message-reformatting""><meta http-equiv=""X-UA-Compatible"" content=""IE=edge""><meta content=""telephone=no"" name=""format-detection""><title>Accepted</title> <!--[if (mso 16)]><style type=""text/css"">     a {text-decoration: none;}     </style><![endif]--> <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><style type=""text/css"">
                @media only screen and (max-width:600px) {p, ul li, ol li, a { font-size:16px!important; line-height:150%!important } h1 { font-size:30px!important; text-align:center; line-height:120%!important } h2 { font-size:26px!important; text-align:center; line-height:120%!important } h3 { font-size:20px!important; text-align:center; line-height:120%!important } h1 a { font-size:30px!important } h2 a { font-size:26px!important } h3 a { font-size:20px!important } .es-menu td a { font-size:16px!important } .es-header-body p, .es-header-body ul li, .es-header-body ol li, .es-header-body a { font-size:16px!important } .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li, .es-footer-body a { font-size:16px!important } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock a { font-size:12px!important } *[class=""gmail-fix""] { display:none!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3 { 
                text-align:center!important } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 { text-align:right!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-button-border { display:block!important } a.es-button { font-size:20px!important; display:block!important; border-width:10px 0px 10px 0px!important } .es-btn-fw { border-width:10px 0px!important; text-align:center!important } .es-adaptive table, .es-btn-fw, .es-btn-fw-brdr, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .es-adapt-td { display:block!important; width:100%!important } .adapt-img { width:100%!important; height:auto!important } .es-m-p0 { padding:0px!important } .es-m-p0r { 
                padding-right:0px!important } .es-m-p0l { padding-left:0px!important } .es-m-p0t { padding-top:0px!important } .es-m-p0b { padding-bottom:0!important } .es-m-p20b { padding-bottom:20px!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { display:table-row!important; width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } .es-desk-menu-hidden { display:table-cell!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } table.es-social { display:inline-block!important } table.es-social td { display:inline-block!important } }#outlook a {	padding:0;}.ExternalClass {	width:100%;}.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {	line-height:100%;}.es-button 
                {	mso-style-priority:100!important;	text-decoration:none!important;}a[x-apple-data-detectors] {	color:inherit!important;	text-decoration:none!important;	font-size:inherit!important;	font-family:inherit!important;	font-weight:inherit!important;	line-height:inherit!important;}.es-desk-hidden {	display:none;	float:left;	overflow:hidden;	width:0;	max-height:0;	line-height:0;	mso-hide:all;}</style></head><body style=""width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0;""><div class=""es-wrapper-color"" style=""background-color:#F6F6F6;""> <!--[if gte mso 9]><v:background xmlns:v=""urn:schemas-microsoft-com:vml"" fill=""t""> <v:fill type=""tile"" color=""#f6f6f6""></v:fill> </v:background><![endif]-->
                <table class=""es-wrapper"" width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;""><tr style=""border-collapse:collapse;""><td valign=""top"" style=""padding:0;Margin:0;""><table class=""es-content"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;""><table class=""es-content-body"" width=""600"" cellspacing=""0"" cellpadding=""0"" bgcolor=""#ffffff"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;""><tr style=""border-collapse:collapse;"">
                <td align=""left"" style=""Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td width=""560"" valign=""top"" align=""center"" style=""padding:0;Margin:0;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;padding-bottom:15px;""><h2 style=""Margin:0;line-height:29px;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:24px;font-style:normal;font-weight:normal;color:#333333;""><strong>Good news&nbsp;" + _donorName + @", we can accept your donation!</strong></h2></td></tr><tr style=""border-collapse:collapse;"">
                <td align=""center"" style=""Margin:0;padding-top:5px;padding-bottom:20px;padding-left:20px;padding-right:20px;font-size:0;""><table border=""0"" width=""100%"" height=""100%"" cellpadding=""0"" cellspacing=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td class=""es-m-txt-c"" align=""center"" style=""padding:5px;Margin:0;font-size:0px;""><img src=""https://iibpvd.stripocdn.email/content/guids/CABINET_787446a06f57203897723d3c9119271f/images/35291590225130102.png"" alt style=""display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;"" width=""200""></td></tr><tr style=""border-collapse:collapse;"">
                <td align=""left"" style=""padding:0;Margin:0;padding-top:20px;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;"">Thank you for your recent offer of your unwanted items to the House2Home project by Helping Hands. Here's what we can accept from what you offered us:<br><br></p><strong>" + _itemList + @"</strong></td></tr><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;""><br>We'll try our best to collect the above items on <strong>" + _collectionDate + "</strong>, and will give you a ring on <strong>" + _donorPhone + @"</strong>
                as soon as we can with&nbsp;an estimated time.<br><br>Thanks again,<br>The Helping Hands Team</p></td></tr><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:20px;Margin:0;font-size:0;""><table border=""0"" width=""100%"" height=""100%"" cellpadding=""0"" cellspacing=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#999999;"">
                House2Home is run by volunteers. A small donation towards your item being collected would be appreciated to keep our charity running.<br><br></p></td></tr><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0;""><a href=""https://uk.virginmoneygiving.com/charity-web/charity/finalCharityHomepage.action?charityId=1015521"" style=""-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:14px;text-decoration:underline;color:#1376C8;""> Click here to donate </a></td></tr><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0;"">
                <a href=""https://docs.google.com/forms/d/e/1FAIpQLSfyGpmIwRakYeLqaN3ZNE9cYXuZsHvseIMGh4GCfz1NllEYOQ/viewform"" style=""-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:14px;text-decoration:underline;color:#1376C8;"">Click here to join our volunteering team</a></td></tr></table></td></tr></table></td></tr></table></td></tr></table><table class=""es-footer"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;"">
                <table class=""es-footer-body"" width=""600"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;""><tr style=""border-collapse:collapse;""><td align=""left"" style=""Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td width=""560"" valign=""top"" align=""center"" style=""padding:0;Margin:0;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:20px;Margin:0;font-size:0;"">
                <table width=""75%"" height=""100%"" cellspacing=""0"" cellpadding=""0"" border=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;padding-top:10px;padding-bottom:10px;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:11px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:17px;color:#333333;"">© 2020 Registered in England: Registration number: 1188613 Charitable Incorporated Organisation (CIO) Name: HELPING HANDS COMMUNITY PROJECT</p></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr>
                </table></div></body>
                </html>
                ";
            }
        }

        public string MessageAcknowledge
        {
            get
            {
                return
                @"
                <!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd""><html style=""width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0;""><head><meta charset=""UTF-8""><meta content=""width=device-width, initial-scale=1"" name=""viewport""><meta name=""x-apple-disable-message-reformatting""><meta http-equiv=""X-UA-Compatible"" content=""IE=edge""><meta content=""telephone=no"" name=""format-detection""><title>New email</title> <!--[if (mso 16)]><style type=""text/css"">     a {text-decoration: none;}     </style><![endif]--> <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><style type=""text/css"">
                @media only screen and (max-width:600px) {p, ul li, ol li, a { font-size:16px!important; line-height:150%!important } h1 { font-size:30px!important; text-align:center; line-height:120%!important } h2 { font-size:26px!important; text-align:center; line-height:120%!important } h3 { font-size:20px!important; text-align:center; line-height:120%!important } h1 a { font-size:30px!important } h2 a { font-size:26px!important } h3 a { font-size:20px!important } .es-menu td a { font-size:16px!important } .es-header-body p, .es-header-body ul li, .es-header-body ol li, .es-header-body a { font-size:16px!important } .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li, .es-footer-body a { font-size:16px!important } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock a { font-size:12px!important } *[class=""gmail-fix""] { display:none!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3 { 
                text-align:center!important } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 { text-align:right!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-button-border { display:block!important } a.es-button { font-size:20px!important; display:block!important; border-width:10px 0px 10px 0px!important } .es-btn-fw { border-width:10px 0px!important; text-align:center!important } .es-adaptive table, .es-btn-fw, .es-btn-fw-brdr, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .es-adapt-td { display:block!important; width:100%!important } .adapt-img { width:100%!important; height:auto!important } .es-m-p0 { padding:0px!important } .es-m-p0r { 
                padding-right:0px!important } .es-m-p0l { padding-left:0px!important } .es-m-p0t { padding-top:0px!important } .es-m-p0b { padding-bottom:0!important } .es-m-p20b { padding-bottom:20px!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { display:table-row!important; width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } .es-desk-menu-hidden { display:table-cell!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } table.es-social { display:inline-block!important } table.es-social td { display:inline-block!important } }#outlook a {	padding:0;}.ExternalClass {	width:100%;}.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div {	line-height:100%;}.es-button 
                {	mso-style-priority:100!important;	text-decoration:none!important;}a[x-apple-data-detectors] {	color:inherit!important;	text-decoration:none!important;	font-size:inherit!important;	font-family:inherit!important;	font-weight:inherit!important;	line-height:inherit!important;}.es-desk-hidden {	display:none;	float:left;	overflow:hidden;	width:0;	max-height:0;	line-height:0;	mso-hide:all;}</style></head><body style=""width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0;""><div class=""es-wrapper-color"" style=""background-color:#F6F6F6;""> <!--[if gte mso 9]><v:background xmlns:v=""urn:schemas-microsoft-com:vml"" fill=""t""> <v:fill type=""tile"" color=""#f6f6f6""></v:fill> </v:background><![endif]-->
                <table class=""es-wrapper"" width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;""><tr style=""border-collapse:collapse;""><td valign=""top"" style=""padding:0;Margin:0;""><table class=""es-content"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;""><table class=""es-content-body"" width=""600"" cellspacing=""0"" cellpadding=""0"" bgcolor=""#ffffff"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;""><tr style=""border-collapse:collapse;"">
                <td align=""left"" style=""Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td width=""560"" valign=""top"" align=""center"" style=""padding:0;Margin:0;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;padding-bottom:15px;""><h2 style=""Margin:0;line-height:29px;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:24px;font-style:normal;font-weight:normal;color:#333333;""><strong>Thanks " + _donorName + @"!</strong></h2></td></tr><tr style=""border-collapse:collapse;"">
                <td class=""es-m-txt-c"" align=""center"" style=""padding:0;Margin:0;font-size:0px;""><img src=""https://iibpvd.stripocdn.email/content/guids/CABINET_787446a06f57203897723d3c9119271f/images/66221590221278255.jpeg"" alt style=""display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;"" width=""560""></td></tr><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;padding-top:20px;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#333333;"">Thank you for your recent offer of your unwanted items to the House2Home project by Helping Hands, we'll be in touch shortly!</p></td></tr><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:20px;Margin:0;font-size:0;"">
                <table border=""0"" width=""100%"" height=""100%"" cellpadding=""0"" cellspacing=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td align=""left"" style=""padding:0;Margin:0;""><p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:14px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;color:#999999;"">House2Home is run by volunteers. A small donation towards your item being collected would be appreciated to keep our charity running.<br><br></p></td></tr><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0;"">
                <a href=""https://uk.virginmoneygiving.com/charity-web/charity/finalCharityHomepage.action?charityId=1015521"" style=""-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:14px;text-decoration:underline;color:#1376C8;""> Click here to donate </a></td></tr><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0;""><a href=""https://docs.google.com/forms/d/e/1FAIpQLSfyGpmIwRakYeLqaN3ZNE9cYXuZsHvseIMGh4GCfz1NllEYOQ/viewform"" style=""-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-size:14px;text-decoration:underline;color:#1376C8;"">Click here to join our volunteering team</a></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
                <table class=""es-footer"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;""><table class=""es-footer-body"" width=""600"" cellspacing=""0"" cellpadding=""0"" align=""center"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;""><tr style=""border-collapse:collapse;""><td align=""left"" style=""Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;"">
                <td width=""560"" valign=""top"" align=""center"" style=""padding:0;Margin:0;""><table width=""100%"" cellspacing=""0"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:20px;Margin:0;font-size:0;""><table width=""75%"" height=""100%"" cellspacing=""0"" cellpadding=""0"" border=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;""><tr style=""border-collapse:collapse;""><td style=""padding:0;Margin:0px 0px 0px 0px;border-bottom:1px solid #CCCCCC;background:none;height:1px;width:100%;margin:0px;""></td></tr></table></td></tr><tr style=""border-collapse:collapse;""><td align=""center"" style=""padding:0;Margin:0;padding-top:10px;padding-bottom:10px;"">
                <p style=""Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-size:11px;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:17px;color:#333333;"">© 2020 Registered in England: Registration number: 1188613 Charitable Incorporated Organisation (CIO) Name: HELPING HANDS COMMUNITY PROJECT</p></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div></body>
                </html>
                ";
            }
        }

    }
}